apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - port: 8123
      targetPort: 8123
      nodePort: 30123
