apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-config
  namespace: home-assistant
  labels:
    app: cloudflare-tunnel
    component: ingress
data:
  config.yaml: |
    tunnel: ha-swe-bit-com-tunnel
    credentials-file: /etc/cloudflared/creds/credentials.json

    ingress:
      # Route ha.swe-bit.com to Home Assistant service
      - hostname: ha.swe-bit.com
        service: http://home-assistant:8123
      # Catch-all rule for any other requests
      - service: http_status:404