apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel
  namespace: home-assistant
  labels:
    app: cloudflare-tunnel
    component: ingress
spec:
  type: ClusterIP
  selector:
    app: cloudflare-tunnel
  ports:
    - name: http
      port: 2000
      targetPort: 2000
      protocol: TCP